# Generated by Django 4.2 on 2026-09-15 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0003_cart_checkout_checkoutlog_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={},
        ),
        migrations.AlterModelOptions(
            name='checkoutlog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='orders_cart_tenant__abdbf5_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='orders_cart_tenant__6c9040_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='orders_cart_cart_to_e1e0a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='orders_cart_tenant__b51d08_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkout',
            name='orders_chec_tenant__b46808_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkout',
            name='orders_chec_tenant__b0c45d_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkout',
            name='orders_chec_cart_id_c446bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkout',
            name='orders_chec_order_i_f282b3_idx',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='completed_steps',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='discount_total',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='payment_gateway_response',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='checkoutlog',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='checkoutlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='checkoutlog',
            name='step',
        ),
        migrations.RemoveField(
            model_name='checkoutlog',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_token',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='billing_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('sslcommerz', 'SSLCommerz'), ('stripe', 'Stripe')], default='cod', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_method',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkoutlog',
            name='log_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cod', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
