# Generated by Django 4.2 on 2026-06-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_products', models.IntegerField()),
                ('max_staff', models.IntegerField()),
                ('max_orders_per_month', models.IntegerField()),
                ('custom_domain', models.BooleanField(default=False)),
                ('ai_recommendation', models.BooleanField(default=False)),
                ('ai_search', models.BooleanField(default=False)),
                ('ai_chatbot', models.BooleanField(default=False)),
                ('ai_analytics', models.BooleanField(default=False)),
                ('ai_demand_forecast', models.BooleanField(default=False)),
                ('ai_dynamic_pricing', models.BooleanField(default=False)),
                ('ai_customer_segmentation', models.BooleanField(default=False)),
                ('ai_churn_prediction', models.BooleanField(default=False)),
                ('ai_fraud_detection', models.BooleanField(default=False)),
                ('ai_content_generator', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trial', 'Trial'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('trial_start', models.DateTimeField()),
                ('trial_end', models.DateTimeField()),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
