# Generated by Django 4.2 on 2026-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('warehouse_location', models.CharField(blank=True, max_length=100)),
                ('shelf_location', models.CharField(blank=True, max_length=50)),
                ('bin_number', models.CharField(blank=True, max_length=50)),
                ('reorder_point', models.IntegerField(default=10)),
                ('reorder_quantity', models.IntegerField(default=50)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('in_transit_quantity', models.IntegerField(default=0)),
                ('damaged_quantity', models.IntegerField(default=0)),
                ('forecast_demand', models.JSONField(blank=True, null=True)),
                ('optimal_stock', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_inventory',
            },
        ),
    ]
