"""
Django settings for xyloshop project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Env ভ্যারিয়েবল রিড
DEBUG = os.getenv('DEBUG', 'True') == 'True'
SECRET_KEY = os.getenv('SECRET_KEY', 'default-insecure-key-for-dev')

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'xyzstore.localhost', 
    'megamart.localhost', 
    'hasibsk.localhost', 
    '.localhost' # এটি দিলে সব সাব-ডোমেইন একসাথে কাজ করবে
]

# ==============================================================================
# APPLICATION DEFINITION (django-tenants Configuration)
# ==============================================================================

SHARED_APPS = [
    'jazzmin',
    'django_tenants',  # এটি অবশ্যই সবার উপরে থাকবে
    'apps.tenants',    # টেন্যান্ট ম্যানেজমেন্ট অ্যাপ
    

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'celery',
    'django_celery_beat',
    
    'apps.subscriptions', # গ্লোবাল সাবস্ক্রিপশন প্ল্যান
]

TENANT_APPS = [
    'django.contrib.contenttypes',  # এটি এখানেও থাকা বাধ্যতামূলক
    'django.contrib.auth',          # টেন্যান্টের নিজস্ব অথেনটিকেশন
    'django.contrib.sessions',

    # 📁 প্রতিটি স্টোরের কাস্টমার/ইউজার আইসোলেশন নিশ্চিত করতে এটি এখানে আনা হলো
    'apps.users',        
    
    # আপনার ইকমার্সের মূল ফিচার এবং বিজনেস লজিক অ্যাপস
    'apps.stores',       
    'apps.products',
    'apps.orders',
    'apps.inventory',
    'apps.customers',
    'apps.ai_engine',
    'apps.analytics',
    'apps.payments',
    'apps.shipping',
    'apps.coupons',
    'apps.reviews',
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware', # ১ নম্বর
    'corsheaders.middleware.CorsMiddleware', # 👈 CORS মিডলওয়্যারটি এখানে যোগ করা সেফ
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL Routing Isolation
ROOT_URLCONF = 'xyloshop.urls'                  # টেন্যান্ট স্কিমার জন্য
PUBLIC_SCHEMA_URLCONF = 'xyloshop.urls_public'   # পাবলিক স্কিমার জন্য

# ==============================================================================
# MULTI-TENANT EXTRA SETTINGS (মিসিং অংশ)
# ==============================================================================
# প্রতিটি টেন্যান্টের মিডিয়া ফাইল আলাদা ফোল্ডারে রাখার জন্য
MULTITENANT_RELATIVE_MEDIA_ROOT = True 


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xyloshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.getenv('DB_NAME', 'xylosaas_ecommerce'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '123321'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# settings.py
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)
TENANT_MODEL = 'tenants.Tenant'
TENANT_DOMAIN_MODEL = 'tenants.Domain'
AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static and Media files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework: Deny-by-default
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # ডিফল্ট প্রোটেকশন
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'tenant_creation': '3/day',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}
# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = False  # Development mode, set to True in production
SESSION_COOKIE_SECURE = False  # Development mode, set to True in production
CSRF_COOKIE_SECURE = False  # Development mode, set to True in production

# সেশন কুকি ডোমেইন এবং সিকিউরিটি ঠিক করুন
SESSION_COOKIE_DOMAIN = None
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

CSRF_COOKIE_DOMAIN = None # অথবা প্রয়োজনে '.localhost'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'



# Celery ConfigurationDATABASE_ROUTERS
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Redis Cache
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@shophive.com')

JAZZMIN_SETTINGS = {
    "site_title": "Xylosaas Admin",
    "site_header": "Xylosaas",
    "site_brand": "Xylosaas Dashboard",
    "login_logo": None,  # চাইলে এখানে লোগোর পাথ দিতে পারেন
    "site_logo_classes": "img-circle",
    
    
    # মেনু সেটিংস
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "tenants", "users"],
    
    # আইকন সেটিংস (মডেলের জন্য সুন্দর আইকন)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "custom_css": "css/custom_admin.css",
    "custom_js": "js/custom_admin.js",

}

# settings.py

# এটি অবশ্যই 'True' হতে হবে
CORS_ALLOW_CREDENTIALS = True 

# ওয়াইল্ডকার্ড ('*') ব্যবহার করবেন না, বরং নির্দিষ্ট ডোমেইন দিন


# অথবা আপনার রেজেক্স সেটিংসটি এমন হওয়া উচিত:
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://.*\.localhost:3000$",
]
CSRF_TRUSTED_ORIGINS = [
    "http://xyzstore.localhost:3000",
    "http://megamart.localhost:3000",
    "http://localhost:3000",
]

# নিচে এগুলোও যোগ করুন যেন Preflight রিকোয়েস্ট (OPTIONS) কাজ করে
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-tenant-id", # আপনার টেন্যান্ট হেডার
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


from celery.schedules import crontab

# Celery Beat Periodic Task Settings
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'daily-subscription-audit': {
        'task': 'apps.subscriptions.tasks.check_expired_subscriptions',
        'schedule': crontab(hour=0, minute=0),  # প্রতিদিন রাত ১২:০০ টায় স্বয়ংক্রিয়ভাবে চলবে
    },
}
