# Generated by Django 4.2 on 2026-09-17 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='announcement_phone',
            field=models.CharField(blank=True, default='+880 1700-000000', max_length=30),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_text',
            field=models.CharField(blank=True, default='Sign up and GET 20% OFF for your first order!', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_announcement_bar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji বা Lucide icon name (যেমন: 🥦)', max_length=50),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='accent_color',
            field=models.CharField(default='#F59E0B', help_text='Warm Amber (#F59E0B)', max_length=7),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='font_family',
            field=models.CharField(default='Inter, sans-serif', max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='primary_color',
            field=models.CharField(default='#059669', help_text='Emerald Green (#059669)', max_length=7),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='secondary_color',
            field=models.CharField(default='#054E34', help_text='Dark Forest Green (#054E34)', max_length=7),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='theme',
            field=models.CharField(choices=[('grocery', 'Fresh Grocery (Default)'), ('fashion', 'Modern Fashion (Premium)'), ('electronics', 'Tech Gadgets (Premium)'), ('minimal', 'Minimalist Clean (Premium)')], default='grocery', max_length=50),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='কাস্টমাইজড থিম ভ্যারিয়েবল ও স্টাইল'),
        ),
        migrations.CreateModel(
            name='StoreTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('designation', models.CharField(default='Verified Buyer', help_text='e.g., Housewife / Regular Customer', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='stores/testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'stores_testimonial',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'stores_faq',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('hero', 'Main Hero Banner'), ('dual_promo', 'Dual Promo Card (Half Width)'), ('deal_of_day', 'Deal of The Day (With Countdown Timer)'), ('wide_offer', 'Wide Offer Strip (Above Best Sellers)')], default='dual_promo', max_length=30)),
                ('badge_title', models.CharField(blank=True, default='Flat 20% Discount', max_length=60)),
                ('title', models.CharField(help_text='e.g., Purely Fresh Vegetables', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='ছোট বিবরণী বা ট্যাগলাইন')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/banners/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('target_url', models.CharField(blank=True, default='/products', max_length=255)),
                ('countdown_end', models.DateTimeField(blank=True, help_text='অফার শেষের ডেট ও টাইম', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'stores_banner',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreNewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'stores_newsletter',
                'ordering': ['-subscribed_at'],
                'unique_together': {('tenant', 'email')},
            },
        ),
        migrations.CreateModel(
            name='StoreBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255)),
                ('category_tag', models.CharField(default='Shopping Tips', help_text='যেমন: Seasonal Guide / Healthy Eating', max_length=60)),
                ('author_name', models.CharField(default='Store Admin', max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stores/blogs/')),
                ('summary', models.TextField(help_text='কার্ডে প্রদর্শিত সংক্ষিপ্ত অংশ')),
                ('content', models.TextField(help_text='মূল ব্লগ কনটেন্ট')),
                ('published_at', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'stores_blog',
                'ordering': ['-published_at'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
