# Generated by Django 4.2 on 2026-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storesettings_announcement_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebanner',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='ডান পাশের ছবি', null=True, upload_to='stores/banners/'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='badge_title',
            field=models.CharField(blank=True, default='Summer Discount', max_length=60),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Main Hero Banner'), ('dual_promo', 'Dual Promo Card (Half Width)'), ('countdown', 'Countdown Discount (Summer Discount)'), ('deal_of_day', 'Deal of The Day (With Countdown Timer)'), ('weekly', 'Weekly Specials Banner (Deep Green)'), ('wide_offer', 'Wide Offer Strip (Above Best Sellers)')], default='countdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='image',
            field=models.ImageField(blank=True, help_text='বাম পাশের ছবি', null=True, upload_to='stores/banners/'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='subtitle',
            field=models.TextField(blank=True, help_text='e.g., Get 50% off - Limited Time Offer!'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='title',
            field=models.CharField(help_text='e.g., Summer Discount', max_length=200),
        ),
    ]
