# Generated by Django 4.2 on 2026-09-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('stores', '0003_storebanner_secondary_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreThemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_key', models.CharField(choices=[('default', 'Modern Clean Grocery/Fashion'), ('classified_soft', 'Soft 3D Clay Classified'), ('neon_studio', 'Cyber Neon Dark Studio')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme_previews/')),
                ('preview_image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='badge_title',
            field=models.CharField(blank=True, default='Flat 20% Discount', max_length=60),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Main Hero Banner (Max 3 for Free Tier)'), ('dual_promo', 'Dual Promo Card (Half Width)'), ('countdown', 'Countdown Discount (Summer Discount)'), ('deal_of_day', 'Deal of The Day (With Countdown Timer)'), ('weekly', 'Weekly Specials Banner (Deep Green)'), ('wide_offer', 'Wide Offer Strip (Above Best Sellers)')], default='hero', max_length=30),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='image',
            field=models.ImageField(blank=True, help_text='মূল ছবি / বাম পাশের ছবি', null=True, upload_to='stores/banners/'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='ডান পাশের ছবি (ঐচ্ছিক)', null=True, upload_to='stores/banners/'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='subtitle',
            field=models.TextField(blank=True, help_text='ছোট বিবরণী বা ট্যাগলাইন'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='title',
            field=models.CharField(help_text='e.g., Purely Fresh Vegetables', max_length=200),
        ),
        migrations.CreateModel(
            name='TenantPurchasedTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_themes', to='tenants.tenant')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storethemetemplate')),
            ],
            options={
                'unique_together': {('tenant', 'theme')},
            },
        ),
    ]
