# Generated by Django 4.2 on 2026-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storethemetemplate_alter_storebanner_badge_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_gallery/')),
            ],
        ),
    ]
