# Generated by Django 4.2 on 2026-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('product_description', 'Product Description'), ('seo_meta', 'SEO Meta'), ('blog_post', 'Blog Post'), ('email', 'Email'), ('social_media', 'Social Media'), ('product_title', 'Product Title')], max_length=50)),
                ('source_data', models.JSONField()),
                ('generated_content', models.TextField()),
                ('ai_metadata', models.JSONField(default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_contents',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('viewed', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_recommendations',
            },
        ),
        migrations.CreateModel(
            name='ChatbotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('was_helpful', models.BooleanField(null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_chatbot_interactions',
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField()),
                ('segment_size', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_frequency', models.FloatField(default=0)),
                ('average_lifetime', models.IntegerField(default=0)),
                ('cluster_id', models.IntegerField()),
                ('cluster_center', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_customer_segments',
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.IntegerField()),
                ('confidence_lower', models.IntegerField()),
                ('confidence_upper', models.IntegerField()),
                ('actual_quantity', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=100)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_demand_forecasts',
            },
        ),
        migrations.CreateModel(
            name='DynamicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('demand_score', models.FloatField(default=0)),
                ('competitor_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('inventory_level', models.IntegerField()),
                ('strategy_used', models.CharField(max_length=100)),
                ('update_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_dynamic_prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('factors', models.JSONField()),
                ('recommendations', models.JSONField(default=list)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_fraud_detections',
            },
        ),
    ]
