# Generated by Django 4.2 on 2026-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio/Voice Note'), ('video', 'Video'), ('document', 'Document/File'), ('call', 'Call Log')], default='text', max_length=20),
        ),
    ]
